In [1]:
#Week 4 HLT Part 1 Question 1: Write a program that allows you to enter 4 numbers and stores them in a file called “Numbers”
my_file = open("Numbers.txt", "w")
a = input('Enter number')
b = input('Enter number')
c = input('Enter number')
d = input('Enter number')
my_file.write(str(a))
my_file.write("\n")
my_file.write(str(b))
my_file.write("\n")
my_file.write(str(c))
my_file.write("\n")
my_file.write(str(d))
my_file.close()


In [1]:
#Week 4 HLT Part 1 Question 2
print("Enter Marks Obtained")
marks = int(input())
if marks>=91 and marks<=100:
    print("Your Grade is A1")
elif marks>=81 and marks<91:
    print("Your Grade is A2")
elif marks>=71 and marks<81:
    print("Your Grade is B1")
elif marks>=61 and marks<71:
    print("Your Grade is B2")
elif marks>=51 and marks<61:
    print("Your Grade is C1")
elif marks>=41 and marks<51:
    print("Your Grade is C2")
elif marks>=33 and marks<41:
    print("Your Grade is D")
elif marks>=21 and marks<33:
    print("Your Grade is E1")
elif marks>=0 and marks<21:
    print("Your Grade is E2")
else:
    print("Invalid Input!")


Enter Marks Obtained
Your Grade is A2


In [18]:
#Week 4 HLT Part 2 Question 1
import numpy as np
x = np.arange(10)
print("Array from 0 to 9:")
print(x)

Array from 0 to 9:
[0 1 2 3 4 5 6 7 8 9]


In [19]:
#Week 4 HLT Part 2 Question 2
number_matrix = np.ones((3,3), dtype=bool)
print(number_matrix)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [37]:
#Week 4 HLT Part 2 Question 3
import numpy as np
a = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) 
a[a%2 == 1]

array([1, 3, 5, 7, 9])

In [31]:
#Week 4 HLT Part 2 Question 4
import numpy as np 
b = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) 
odd_values = (b%2 == 1) 
b[odd_values] = -1 
print(b)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [44]:
#Week 4 HLT Part 2 Question 5
import numpy as np
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array_2rows = np.reshape(array, (2, 5))
print(array_2rows)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [59]:
#Week 4 HLT Part 2 Question 6
a = np.arange (1,10).reshape (3,3)  
b = np.arange (10,19).reshape (3,3) 
outputs = np.vstack((a, b))
print(outputs)
sum = np.sum(c)  
print(sum)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
1944
